steps:
  - name: 'gcr.io/cloud-marketplace-containers/google/bazel'
    entrypoint: "bash"
    args: ['-c', './ci.sh']

  - name: 'gcr.io/cloud-solutions-images/apache-airflow:1.10'
    entrypoint: 'python'
    args: ['test_compare_xcom_maps.py']
    dir: '$REPO_NAME/workflow-dag'
    id: 'unit-test-on-operator-code'