package(default_visibility = ["//visibility:public"])
load("@subpar//:subpar.bzl", "par_binary")

py_binary(
    name = 'bigquery_github_trends',
    srcs = ["bigquery_github_trends.py"],
    main = "bigquery_github_trends.py"
)
